id: P330B3E49
initial_creation_type: ocr
source_metadata:
  volumes:
    fa10be82d28142da9672981480320940:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: དམིགས་པ་བརྟག་པའི་འགྲེལ་པ།
      total_pages: 1198
      volume_number: 97
